/**************
  Generated by wav2bin tools 0.002
  Generated time：20230220
  Generated name：C:/work/copyFromDell/??/?????/soundec wav-16K16bit-???/soundec_wav.bin
  Suggest 8khz 16bit single track tones
  Total lenth：306432 bytes
**************/ 


#ifndef __SOUNDEC_WAV_H__
#define __SOUNDEC_WAV_H__


#define TONES_TOTAL_NUM          12
#define TONES_SAMPLERATE         16000  // suggest 8KHZ
#define TONES_BPS                16     //suggest 16bit
#define TONES_BIN_TOTAL_SIZE     0x4ad00


typedef enum
{
    SOUNDEC_WAV_BT_CONNECTED,
    SOUNDEC_WAV_BT_DISCONNECTED,
    SOUNDEC_WAV_MUTE,
    SOUNDEC_WAV_NEXT,
    SOUNDEC_WAV_PAUSE,
    SOUNDEC_WAV_PLAY,
    SOUNDEC_WAV_POWER_OFF,
    SOUNDEC_WAV_POWER_ON,
    SOUNDEC_WAV_PREV,
    SOUNDEC_WAV_SW_MODE,
    SOUNDEC_WAV_VOL_DOWN,
    SOUNDEC_WAV_VOL_UP,
}SOUNDEC_WAV_TONES_ID;



#endif //__SOUNDEC_WAV_H__

