/**************
  Generated by wav2bin tools 0.001
  Generated time：20211215
  Generated name：D:/Tools/packWav2Bin/DCwav/DC_wav.bin
  Suggest 8khz 16bit single track tones
  Total lenth：284272 bytes
**************/ 


#ifndef __DC_WAV_H__ 
#define __DC_WAV_H__

#define TONES_TOTAL_NUM          14
#define TONES_SAMPLERATE         8000  // suggest 8KHZ
#define TONES_BPS                16     //suggest 16bit
#define TONES_BIN_TOTAL_SIZE     0x3ae10


typedef enum
{
    DC_WAV_HEADPHONES_CLASSIC,
    DC_WAV_HEADPHONES_DEFAULT,
    DC_WAV_HEADPHONES_JAZZ,
    DC_WAV_HEADPHONES_MODE,
    DC_WAV_HEADPHONES_MUTE,
    DC_WAV_HEADPHONES_POP,
    DC_WAV_HEADPHONES_ROCK,
    DC_WAV_MICROPHONE_DEFAULT,
    DC_WAV_MICROPHONE_MODE,
    DC_WAV_MICROPHONE_MONITOR,
    DC_WAV_MICROPHONE_MUTE,
    DC_WAV_MICROPHONE_NOISE_CANCELLATION,
    DC_WAV_VOLUME_DOWN,
    DC_WAV_VOLUME_UP,
}DC_WAV_TONES_ID;



#endif //__DC_WAV_H__

