/**************
  Generated by wav2bin tools 0.001
  Generated time：20221009
  Generated name：D:/Tools/packWav2Bin/8K8bit/wav_8k8bit.bin
  Suggest 8khz 16bit single track tones
  Total lenth：36528 bytes
**************/ 


#ifndef __WAV_8K8BIT_H__ 
#define __WAV_8K8BIT_H__

#define TONES_TOTAL_NUM          4
#define TONES_SAMPLERATE         8000  // suggest 8KHZ
#define TONES_BPS                8     //suggest 16bit
#define TONES_BIN_TOTAL_SIZE     0x8eb0


typedef enum
{
    WAV_8K8BIT_HEADPHONES_CLASSIC,
    WAV_8K8BIT_HEADPHONES_DEFAULT,
    WAV_8K8BIT_HEADPHONES_JAZZ,
    WAV_8K8BIT_HEADPHONES_MODE,
}WAV_8K8BIT_TONES_ID;



#endif //__WAV_8K8BIT_H__

